name: youtube-live-streamer
base: core20
summary: YouTube Live Streamer
adopt-info: streamer
description: |
  Intended to help stream your IP Cam to YouTube Live.
  _Note: only cams with h264 codec are supported at the moment_

  **Getting started**
  0. [RaspberryPi + Raspbian/Raspberry Pi OS] Update `snapd` to the latest available version according to https://forum.snapcraft.io/t/installing-snap-on-debian
  1. Install snap: `sudo snap install youtube-live-streamer --edge`
  2. Get `stream key` in YouTube Studio (https://studio.youtube.com/channel/UC/livestreaming)
  3. Open config file for edit: `sudoedit /var/snap/youtube-live-streamer/common/live-streamer.conf`
  4. Replace `source` value with desired RTSP URL
  5. Uncomment `youtube-stream-key: "xxxx-xxxx-xxxx-xxxx-xxxx"` line by removing `#` at the beginning and replace `xxxx-xxxx-xxxx-xxxx-xxxx` with your `stream key`
  6. Restart snap: `sudo snap restart youtube-live-streamer`

  **Troubleshooting**
  * Look to the logs with `sudo snap logs youtube-live-streamer` or `sudo snap logs youtube-live-streamer -f`
  * Create issue on https://github.com/RSATom/YouTubeLiveStreamer/issues
license: GPL-3.0
grade: devel
confinement: strict

architectures:
  - build-on: amd64
#  - build-on: i386
  - build-on: armhf
  - build-on: arm64

environment:
  GST_DEBUG: 3
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/libexec/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0/gst-plugin-scanner
  LD_LIBRARY_PATH: $SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/opt/${SNAP_NAME}/lib
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0

parts:
  streamer:
    plugin: cmake
    source-type: git
    source: https://github.com/RSATom/YouTubeLiveStreamer.git
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version "$(git describe --always)"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - pkg-config
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
      - libgstreamer1.0-dev
    stage-packages:
      - libconfig9
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad

apps:
  YouTubeLiveStreamer:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/YouTubeLiveStreamer
    daemon: simple
    plugs:
      - network
